In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
import keras_tuner as kt

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import r2_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sqlalchemy import create_engine, func

from Config import password

# Ignore warning messages
import warnings
warnings.filterwarnings("ignore")

In [2]:
alchemy_engine = create_engine(f'postgresql://postgres:{password}@localhost:5432/SolarDB')

In [3]:
input_df = pd.read_sql_query('SELECT * FROM solar_data_v2 WHERE solar_data_v2 is not NULL;', alchemy_engine)
input_df = input_df.rename({"InvVDCin_Avg":"Voltage_Output"}, axis=1)
input_df = input_df.drop("TIMESTAMP", axis=1)
input_df

,Year,Month,Day,Hour,Minute,GHI,DHI,DNI,Wind Speed,Temperature,Cloud Type,Solar Zenith Angle,Surface Albedo,Wind Direction,Pressure,Relative Humidity,Precipitable Water,Voltage_Output,Array_Tilt
0,2015,1,1,0,30,0.0,0.0,0.0,1.6,-3.0,0.0,163.45,0.129,254.0,1000.0,73.50,0.381,21.000,5
1,2015,1,1,2,0,0.0,0.0,0.0,1.7,-3.0,0.0,152.03,0.129,235.4,1000.0,73.72,0.380,20.960,5
2,2015,1,1,3,30,0.0,0.0,0.0,1.6,-3.0,0.0,135.31,0.129,234.2,1000.0,74.25,0.381,21.160,5
3,2015,1,1,4,0,0.0,0.0,0.0,1.6,-4.0,0.0,129.51,0.129,232.1,1000.0,80.47,0.382,20.720,5
4,2015,1,1,10,30,416.0,64.0,885.0,3.7,1.0,0.0,66.57,0.129,233.7,1000.0,51.62,0.424,384.200,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190547,2018,3,18,17,30,122.0,38.0,552.0,0.8,8.2,0.0,81.28,0.130,300.0,998.0,0.70,66.090,370.600,10
190548,2018,3,18,18,30,0.0,0.0,0.0,0.9,7.3,0.0,92.98,0.130,298.0,998.0,0.70,53.830,280.000,10
190549,2018,3,18,21,0,0.0,0.0,0.0,1.1,4.4,0.0,120.91,0.120,266.0,998.0,0.60,63.000,-1.450,10
190550,2018,3,18,23,0,0.0,0.0,0.0,1.3,2.1,0.0,137.65,0.120,283.0,998.0,0.70,73.570,-1.700,10
190551,2018,3,18,23,30,0.0,0.0,0.0,1.3,1.8,0.0,139.99,0.120,291.0,998.0,0.70,75.160,-1.767,10

In [4]:
input_df.dtypes

Year                    int64
Month                   int64
Day                     int64
Hour                    int64
Minute                  int64
GHI                   float64
DHI                   float64
DNI                   float64
Wind Speed            float64
Temperature           float64
Cloud Type            float64
Solar Zenith Angle    float64
Surface Albedo        float64
Wind Direction        float64
Pressure              float64
Relative Humidity     float64
Precipitable Water    float64
Voltage_Output        float64
Array_Tilt              int64
dtype: object

In [13]:
y = input_df["Voltage_Output"].values
X = input_df.drop(["Voltage_Output"],1).values
input_features = (len(input_df.columns)-1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=27)

In [5]:
# Initialize and fit the scaler object
scaler = StandardScaler()

train_scaled = scaler.fit_transform(X_train)
test_scaled = scaler.transform(X_test)

NameError: name 'X_train' is not defined

In [6]:
model = MLPRegressor()

NameError: name 'MLPRegressor' is not defined